version: "3.7"
services:
  
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.1-bionic
    environment:
      # Don't be confused, mariadb is compatible to mysql and shares cmds
      MYSQL_ROOT_PASSWORD: mariaPW
      TZ: UTC
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4
    volumes:
      - ./mariadb/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: on-failure

  wildfly:
    depends_on:
      - mariadb
    container_name: wildfly
    build: ./wildfly-docker
    environment:
        - KEYCLOAK_SERVER_URL=http://keycloak:8080
    ports:
      - "8180:8080"
      - "9990:9990"
  
  keycloak:
    container_name: keycloak
    image: 'jboss/keycloak:10.0.1'
    environment:
      - DB_VENDOR=h2 # DB_Vendor must be set to avoid startup crashes in this case
      - KEYCLOAK_PASSWORD=nimda
      - KEYCLOAK_USER=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      # Use a different default port than wildfly
      - "8080:8080"
      - "8443:8443"
